### PR TITLE
Bug sign up isssue 701

### LINKED ISSUE #701: BUG: Can create more than one account with same email/phone
Currently a user can create more than one account using the same email/phone. We need to make sure that when entering an email that is already registered on the device, we warn the user and stop them from continuing.

### PR DESCRIPTION
**Pull request by EngrTaofeek**
Fixed bug that allows user to bypass credential validation by pressing Go on the keyboard which
 skips validation.

Fixed bug that allowed user to create  multiple accounts with same plant identifier.
Fixes #701

### CODE REVIEW

File: app/src/main/java/org/greenstand/android/TreeTracker/database/TreeTrackerDAO.kt [hunk 1]
```diff
@@ -33,9 +33,15 @@ interface TreeTrackerDAO {
     @Query("SELECT * FROM planter_info WHERE _id = :id")
     suspend fun getPlanterInfoById(id: Long): PlanterInfoEntity?
 
+    @Query("SELECT * FROM planter_info WHERE planter_identifier = :identity")
+    suspend fun getPlanterInfoById(identity: String): PlanterInfoEntity?
```
Comment (Elforama) [inline app/src/main/java/org/greenstand/android/TreeTracker/database/TreeTrackerDAO.kt:37]: Can we rename this to getPlanterInfoByIdentifier? Otherwise it can get confusing with the other method of the same name.

File: app/src/main/java/org/greenstand/android/TreeTracker/database/TreeTrackerDAO.kt [hunk 2]
```diff
@@ -33,9 +33,15 @@ interface TreeTrackerDAO {
...
+
     @Query("SELECT * FROM planter_info WHERE power_user = 1")
     suspend fun getPowerUser(): PlanterInfoEntity?
 
+    @Query("SELECT COUNT(*) FROM planter_info WHERE planter_identifier = :identifier LIMIT 1")
+    suspend fun checkIfPlanterExists(identifier: String): Int
```
Comment (Elforama) [inline app/src/main/java/org/greenstand/android/TreeTracker/database/TreeTrackerDAO.kt:43]: We don't need this method. We can use the other method you created, and check if it returns null or not.

File: app/src/main/java/org/greenstand/android/TreeTracker/models/user/Users.kt [hunk 3]
```diff
@@ -87,6 +93,10 @@ class Users(
         }
     }
 
+    suspend fun checkPlanterExists(identifier: String): Boolean{
+        return dao.checkIfPlanterExists(identifier) >= 1
+    }
```
Comment (Elforama) [inline app/src/main/java/org/greenstand/android/TreeTracker/models/user/Users.kt:98]: No need for this, just check for a nonnull user from getUserWithIdentifier. There can only ever be one user per identifier/wallet

File: app/src/main/java/org/greenstand/android/TreeTracker/signup/CredentialEntryView.kt [hunk 4]
```diff
@@ -105,11 +115,11 @@ fun CredentialEntryView(viewModel: SignupViewModel, state: SignUpState) {
                     placeholder = { Text(text = stringResource(id = R.string.email_placeholder), color = Color.White) },
                     keyboardOptions = KeyboardOptions(
                         keyboardType = KeyboardType.Email,
-                        imeAction = ImeAction.Go,
+                        imeAction = ImeAction.Done,
```
Comment (Elforama) [inline app/src/main/java/org/greenstand/android/TreeTracker/signup/CredentialEntryView.kt:118]: Why did you change this? 'done' usually means you completed something, but in this case we go to the next input.

File: app/src/main/java/org/greenstand/android/TreeTracker/signup/CredentialEntryView.kt [hunk 5]
```diff
@@ -175,6 +185,53 @@ fun <T : Credential> CredentialButton(
...
+                UserButton(
+                    user = it,
+                    isSelected = false,
+                    AppButtonColors.Default,
+                    Green
+                ) {
+                    navController.navigate(NavRoute.Dashboard.route) {
+                        popUpTo(NavRoute.Language.route) { inclusive = true }
+                        launchSingleTop = true
+                    }
```
Comment (Elforama) [inline app/src/main/java/org/greenstand/android/TreeTracker/signup/CredentialEntryView.kt:218]: It looks like if we click on an existing user, we then instantly log them out. We should log them in, and go to the wallet screen.

**Review by Elforama — CHANGES_REQUESTED** [review]
Looking good. Just a few things to fix.

File: app/src/main/java/org/greenstand/android/TreeTracker/database/TreeTrackerDAO.kt (hunk 1 above)
Comment (EngrTaofeek) [reply app/src/main/java/org/greenstand/android/TreeTracker/database/TreeTrackerDAO.kt:37]: Okay I didn't know there was an existing method with same name

File: app/src/main/java/org/greenstand/android/TreeTracker/models/user/Users.kt [hunk 6]
```diff
@@ -94,7 +94,7 @@ class Users(
     }
 
     suspend fun checkPlanterExists(identifier: String): Boolean{
```
Comment (Elforama) [inline app/src/main/java/org/greenstand/android/TreeTracker/models/user/Users.kt:96]: rename to doesUserExist() or something with "user" in the name.

File: app/src/main/java/org/greenstand/android/TreeTracker/signup/CredentialEntryView.kt [hunk 7]
```diff
@@ -212,8 +212,8 @@ fun ExistingUserDialog(
                     AppButtonColors.Default,
                     Green
                 ) {
-                    navController.navigate(NavRoute.Dashboard.route) {
-                        popUpTo(NavRoute.Language.route) { inclusive = true }
+                    navController.navigate(NavRoute.WalletSelect.create(it.id)) {
+                        popUpTo(NavRoute.SignupFlow.route) { inclusive = true }
```
Comment (Elforama) [inline app/src/main/java/org/greenstand/android/TreeTracker/signup/CredentialEntryView.kt:216]: Let's rename "it" to "user" so we know what it is easier.

**Review by Elforama — CHANGES_REQUESTED** [review]

**Review by Elforama — APPROVED** [review]
Looks great! Thank you
