### PR TITLE
Fixed message feature arrow buttons in action bar and purple highlight

### LINKED ISSUE #872: Update action bars and temporary selected color
The arrow buttons and highlighted UserButton contain a bit of default tracking colour as shown below
Screenshot_1646320209
Screenshot_1646320214

### PR DESCRIPTION
**Pull request by EngrTaofeek**
fixes #872  Fixed message feature arrow buttons in action bar and purple highlight for userSelect button.

### CODE REVIEW

File: app/src/main/java/org/greenstand/android/TreeTracker/view/TextButton.kt [hunk 1]
```diff
@@ -65,12 +63,33 @@ fun BoxScope.ArrowButton(
...
                 .size(height = 45.dp, width = 45.dp),
-            painter = if (isLeft) painterResource(id = R.drawable.arrow_left_green) else painterResource(id = R.drawable.arrow_right_green),
+            painter = getPainter(colors = colors, isLeft = isLeft),
             contentDescription = null,
         )
     }
 }
 
+@Composable
+fun getPainter(colors: ButtonColors, isLeft: Boolean): Painter {
```
Comment (Elforama) [inline app/src/main/java/org/greenstand/android/TreeTracker/view/TextButton.kt:73]: Please make this private. It should not be accessed outside this file.

**Review by Elforama — APPROVED** [review]
Looks good
